### ISSUE TITLE
Duplicated entries in the wheel

### ISSUE THREAD

**Issue by FFY00** [FFY00/mesonpy#13]
There are a couple duplicated names being entered to the wheel. I have identified the most problematic issue, which as cause due to a mistake I made in the Meson introspection and should be fixed by https://github.com/mesonbuild/meson/pull/9474.

Right now, we still have one entry, I need to investigate:
```
WARNING Duplicate name: 'scipy/sparse/linalg/tests/__init__.py'
```

**Comment by FFY00** [comment]
Ugh, I must be blind! This is not a Meson bug, it was a bug in the SciPy build system, which is fixed now :persevere:

**Comment by rgommers** [comment]
Sorry about that! There may be a few more bugs lurking there, we'll find them when more people start using Meson builds on various distros/configs.

**Comment by FFY00** [comment]
Yeah, but I looked at these files and somehow missed this :confused:
