### ISSUE TITLE
Selecting the correct ABI tag

### ISSUE THREAD

**Issue by FFY00** [FFY00/mesonpy#16]
Selecting the ABI tag is not as straight forward as I hoped it could be.

Firstly, there are two main possible ABIs, the interpreter specific ABI, and the stable ABI. The stable ABI uses the `abi3` tag and is compatible across Python minor versions.

Secondly, there are many variants of the interpreter specific ABI, we need to detect that. I think the easier way is to do this is by looking at the extensions of the native modules.

And lastly, we will need to detect the ABI via the file extensions, but this is only standardized on Posix, via [PEP 3149](https://www.python.org/dev/peps/pep-3149). PEP 3149 is optional on Windows, but from what I have seen everyone seems to use it on Windows.

So, supporting this will consist on the following:
1) Identify and parse the ABI from native modules
2) Check incompatible that
3) Identify and select the more specific tag (interpreter tag over the stable ABI)

**Comment by FFY00** [comment]
I am implementing this, but it's showing itself even more difficult than expected, as we need to hardcode support for all possible values, which is difficult to make sure we get right without anything important missing.

**Comment by rgommers** [comment]
That sounds painful. Is there no place where this can be retrieved from? I've seen the "SOABI tags are incorrect for musl" thread, but I'd expect that aside from bugs like that it'd not be something that one would need to hardcode in every build system.

**Comment by FFY00** [comment]
Well, usually build systems know what they are building, so they can generate the correct tag. Our problem is that we don't have any control over this, as one could build anything with Meson, which is a far more versatile and complex build system than any Python-specific one. We need to look at the files we get from Meson and figure out the correct ABI tag for the well.

This could have been a little easier if the PEP 3149 library name matched, or included, the ABI tag string, but it doesn't, it's a slightly different format. So we need to parse the names and generate the equivalent tag, and to make things more manageable, as Meson projects can be very complex, we should probably try to identify any incompatibilities and either fail or issue warnings to the user.

**Comment by FFY00** [comment]
During this I have noticed that PyPy uses custom Python tags (eg, pp272), so we will need to handle that too :upside_down_face:

**Comment by FFY00** [comment]
Opened  #17
