### ISSUE TITLE
Meson does not run with the expected Python executable

### ISSUE THREAD

**Issue by FFY00** [FFY00/mesonpy#23]
One of the problems of Meson's handling of Python is that `find_program`, which is also used by Meson Python module, will find whatever Python executable is available, which is not necessarily the one we are using. Because of this, Meson might actually build native modules for a different Python version than we are using, and also there may be some mismatch in the paths returned by Meson and the ones we were expecting.

Currently, our heuristics should be able to work around the path mismatch issue, but that is not a long-term solution. That said, Meson building native modules for a different version is very much an issue and should be fixed.

We need to make Meson use the current Python interpreter.

**Comment by rgommers** [comment]
Thanks. I haven't seen this happen yet, but I can imagine it does. So yes, using the current interpreter should be right. For direct invocations of `meson` I can imagine that a global `meson` install can work outside of the Python environment it's installed in. But for `mesonpy` it should always be the current interpreter if we're not cross-compiling.

**Comment by FFY00** [comment]
I think the main problem is that even if Meson is working inside a Python environment, it can still pick a Python outside (depends on the `PATH` environment variable IIRC).
